version: '2'
services:
    matricula-app:
        build: .
        container_name: "matricula"
        image: adsantos/matricula
        environment:
            - NODE_ENV=development
            - AWS_ACCESS_KEY_ID=<key>
            - AWS_SECRET_ACCESS_KEY=<secret>
        ports:
            - 3000:3000
        links:
            - mongodb-srv
        depends_on:
            - mongodb-srv
    mongodb-srv:
        image: mongo:latest
        container_name: "mongodb-srv"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
