apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: matricula
  name: matricula
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matricula
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: matricula
    spec:
      containers:
        - image: adsantos/matricula:latest
          imagePullPolicy: Always
          name: matricula
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ms-matricula
  labels:
    name: matricula
spec:
  clusterIP: None
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app: matricula
---
apiVersion: v1
kind: Service
metadata:
  name: ms-matricula-lb
  labels:
    name: matricula-lb
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app: matricula
